name: Update Checker

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schedule:
#    - cron: 0 */18 * * *

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3 # Use the latest version of checkout action

    - name: Get and Compare Commit Hash
      id: cacheHash
      run: |
        git rev-parse HEAD > .commitHash
        hash=$(cat .commitHash)
        echo "::set-output name=commitHash::${hash}"
      uses: actions/cache@v2
      with:
        path: .commitHash
        key: ${{ runner.os }}-${{ steps.cacheHash.outputs.commitHash }}

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Source Code Update

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@v1.1 # Use the latest version of delete-workflow-runs action
      with:
        retain_days: 1
        keep_minimum_runs: 1

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v2 # Use the latest version of ssh2actions action
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
